require File.expand_path('../commands/command', __FILE__)
require File.expand_path('../commands/user_command', __FILE__)
require File.expand_path('../commands/contact_command', __FILE__)
require File.expand_path('../commands/report_command', __FILE__)
require File.expand_path('../commands/implosion_command', __FILE__)
